package deposit

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	_ "github.com/lib/pq"
	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/apex/mcd/internal/ledger"
	"github.com/apex/mcd/internal/models"
	"github.com/apex/mcd/internal/notification"
	"github.com/apex/mcd/internal/state"
)

// getReturnTestDB opens a Postgres connection for return tests, skipping if unavailable.
func getReturnTestDB(t *testing.T) *sql.DB {
	t.Helper()
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		dsn = "postgres://mcd:mcd@localhost:5432/mcd?sslmode=disable"
	}
	db, err := sql.Open("postgres", dsn)
	if err != nil {
		t.Skipf("skipping return test: cannot open postgres: %v", err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		db.Close()
		t.Skipf("skipping return test: postgres not reachable: %v", err)
	}
	return db
}

// insertCompletedTransfer inserts a transfer in completed state for return testing.
func insertCompletedTransfer(t *testing.T, db *sql.DB, amountCents int64) uuid.UUID {
	t.Helper()
	id := uuid.New()
	_, err := db.ExecContext(context.Background(), `
		INSERT INTO transfers
			(id, account_id, amount_cents, declared_amount_cents, status)
		VALUES ($1, $2, $3, $4, 'completed')`,
		id, "ACC-SOFI-1006", amountCents, amountCents)
	require.NoError(t, err, "insertCompletedTransfer")
	return id
}

// cleanupReturnTransfer removes a test transfer and all related rows.
func cleanupReturnTransfer(t *testing.T, db *sql.DB, id uuid.UUID) {
	t.Helper()
	db.ExecContext(context.Background(), `DELETE FROM notifications WHERE transfer_id = $1`, id.String())
	db.ExecContext(context.Background(), `DELETE FROM ledger_entries WHERE transfer_id = $1`, id)
	db.ExecContext(context.Background(), `DELETE FROM state_transitions WHERE transfer_id = $1`, id)
	db.ExecContext(context.Background(), `DELETE FROM transfers WHERE id = $1`, id)
}

// ── Pure unit tests (no DB required) ─────────────────────────────────────────

// TestReturn_ReasonsEndpoint_ReturnsAllCodes verifies that ReturnReasons contains
// all expected codes and that each entry is fully populated.
func TestReturn_ReasonsEndpoint_ReturnsAllCodes(t *testing.T) {
	expectedCodes := []string{
		"insufficient_funds", "account_closed", "stop_payment",
		"signature_mismatch", "stale_dated", "unable_to_locate", "frozen_account",
	}
	require.Len(t, models.ReturnReasons, len(expectedCodes),
		"ReturnReasons must contain exactly %d entries", len(expectedCodes))

	for i, r := range models.ReturnReasons {
		assert.Equal(t, expectedCodes[i], r.Code, "reason[%d] code mismatch", i)
		assert.NotEmpty(t, r.Label, "reason[%d] Label must not be empty", i)
		assert.NotEmpty(t, r.Description, "reason[%d] Description must not be empty", i)
	}
}

// TestReturn_InvalidReasonCode_Returns422 verifies that ValidReturnReasonCode returns
// nil for an unknown code, enabling the handler to return 422.
func TestReturn_InvalidReasonCode_Returns422(t *testing.T) {
	result := models.ValidReturnReasonCode("not_a_real_reason")
	assert.Nil(t, result, "unknown reason code must return nil")

	result2 := models.ValidReturnReasonCode("")
	assert.Nil(t, result2, "empty reason code must return nil")
}

// TestReturn_BankReferenceAutoGenerated verifies that the Return handler generates
// a bank_reference when none is provided in the request body.
func TestReturn_BankReferenceAutoGenerated(t *testing.T) {
	db := getReturnTestDB(t)
	defer db.Close()

	id := insertCompletedTransfer(t, db, 100000)
	defer cleanupReturnTransfer(t, db, id)

	gin.SetMode(gin.TestMode)
	r := gin.New()
	svc := NewService(db, state.New(db), nil, nil, ledger.NewService(db))
	handler := NewHandler(svc, Config{ReturnFeeCents: 3000}, notification.NewRepo(db))
	r.POST("/deposits/:id/return", handler.Return)

	body, _ := json.Marshal(map[string]string{
		"reason_code": "stop_payment",
		// bank_reference intentionally omitted
	})
	req := httptest.NewRequest(http.MethodPost, "/deposits/"+id.String()+"/return", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	require.Equal(t, http.StatusOK, w.Code)

	var resp map[string]any
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &resp))
	data := resp["data"].(map[string]any)
	bankRef, ok := data["bank_reference"].(string)
	require.True(t, ok, "bank_reference must be a string")
	assert.NotEmpty(t, bankRef, "bank_reference must be auto-generated when not provided")
	assert.Contains(t, bankRef, "RET-", "auto-generated bank reference should start with RET-")
}

// ── Service-level tests (require Postgres) ────────────────────────────────────

// TestReturn_InsufficientFunds_ReversalAndFeePosted verifies that returning a deposit
// with "insufficient_funds" transitions the transfer to returned and posts reversal entries.
func TestReturn_InsufficientFunds_ReversalAndFeePosted(t *testing.T) {
	db := getReturnTestDB(t)
	defer db.Close()

	id := insertCompletedTransfer(t, db, 150000)
	defer cleanupReturnTransfer(t, db, id)

	svc := NewService(db, state.New(db), nil, nil, ledger.NewService(db))
	transfer, err := svc.ProcessReturn(context.Background(), id, "insufficient_funds", 3000)
	require.NoError(t, err)
	assert.Equal(t, models.StatusReturned, transfer.Status)

	require.NotNil(t, transfer.ReturnReason)
	assert.Equal(t, "insufficient_funds", *transfer.ReturnReason)

	var count int
	err = db.QueryRowContext(context.Background(),
		`SELECT COUNT(*) FROM ledger_entries WHERE transfer_id = $1`, id).Scan(&count)
	require.NoError(t, err)
	assert.Equal(t, 2, count, "return must create exactly 2 ledger entries (REVERSAL + RETURN_FEE)")
}

// TestReturn_AccountClosed_ReversalAndFeePosted verifies the return flow for account_closed.
func TestReturn_AccountClosed_ReversalAndFeePosted(t *testing.T) {
	db := getReturnTestDB(t)
	defer db.Close()

	id := insertCompletedTransfer(t, db, 200000)
	defer cleanupReturnTransfer(t, db, id)

	svc := NewService(db, state.New(db), nil, nil, ledger.NewService(db))
	transfer, err := svc.ProcessReturn(context.Background(), id, "account_closed", 3000)
	require.NoError(t, err)
	assert.Equal(t, models.StatusReturned, transfer.Status)
}

// TestReturn_StopPayment_ReversalAndFeePosted verifies the return flow for stop_payment.
func TestReturn_StopPayment_ReversalAndFeePosted(t *testing.T) {
	db := getReturnTestDB(t)
	defer db.Close()

	id := insertCompletedTransfer(t, db, 75000)
	defer cleanupReturnTransfer(t, db, id)

	svc := NewService(db, state.New(db), nil, nil, ledger.NewService(db))
	transfer, err := svc.ProcessReturn(context.Background(), id, "stop_payment", 3000)
	require.NoError(t, err)
	assert.Equal(t, models.StatusReturned, transfer.Status)
}

// TestReturn_NonCompletedDeposit_Returns409 verifies that ProcessReturn returns
// ErrTransferNotReturnable when the transfer is not in Completed state.
func TestReturn_NonCompletedDeposit_Returns409(t *testing.T) {
	db := getReturnTestDB(t)
	defer db.Close()

	// Insert a transfer in funds_posted state (not completed).
	id := uuid.New()
	_, err := db.ExecContext(context.Background(), `
		INSERT INTO transfers
			(id, account_id, amount_cents, declared_amount_cents, status)
		VALUES ($1, $2, $3, $4, 'funds_posted')`,
		id, "ACC-SOFI-1006", 100000, 100000)
	require.NoError(t, err)
	defer cleanupReturnTransfer(t, db, id)

	svc := NewService(db, state.New(db), nil, nil, ledger.NewService(db))
	_, err = svc.ProcessReturn(context.Background(), id, "insufficient_funds", 3000)
	require.Error(t, err)
	assert.ErrorIs(t, err, models.ErrTransferNotReturnable,
		"non-completed deposit must return ErrTransferNotReturnable")
}

// TestReturn_LedgerEntries_CorrectAmounts verifies REVERSAL and RETURN_FEE entry amounts.
func TestReturn_LedgerEntries_CorrectAmounts(t *testing.T) {
	db := getReturnTestDB(t)
	defer db.Close()

	const depositAmount = int64(100000) // $1,000.00
	const returnFee = int64(3000)       // $30.00

	id := insertCompletedTransfer(t, db, depositAmount)
	defer cleanupReturnTransfer(t, db, id)

	svc := NewService(db, state.New(db), nil, nil, ledger.NewService(db))
	_, err := svc.ProcessReturn(context.Background(), id, "signature_mismatch", returnFee)
	require.NoError(t, err)

	rows, err := db.QueryContext(context.Background(),
		`SELECT sub_type, amount_cents FROM ledger_entries WHERE transfer_id = $1`, id)
	require.NoError(t, err)
	defer rows.Close()

	entryAmounts := map[string]int64{}
	for rows.Next() {
		var subType string
		var amount int64
		require.NoError(t, rows.Scan(&subType, &amount))
		entryAmounts[subType] = amount
	}
	require.NoError(t, rows.Err())

	assert.Equal(t, depositAmount, entryAmounts["REVERSAL"],
		"REVERSAL entry must equal the original deposit amount")
	assert.Equal(t, returnFee, entryAmounts["RETURN_FEE"],
		"RETURN_FEE entry must equal the configured return fee")
}

// TestReturn_TransferStateTransition_CompletedToReturned verifies that a state transition
// row is written for the Completed→Returned change.
func TestReturn_TransferStateTransition_CompletedToReturned(t *testing.T) {
	db := getReturnTestDB(t)
	defer db.Close()

	id := insertCompletedTransfer(t, db, 50000)
	defer cleanupReturnTransfer(t, db, id)

	svc := NewService(db, state.New(db), nil, nil, ledger.NewService(db))
	_, err := svc.ProcessReturn(context.Background(), id, "stale_dated", 3000)
	require.NoError(t, err)

	var fromState, toState string
	err = db.QueryRowContext(context.Background(), `
		SELECT from_state, to_state FROM state_transitions
		WHERE transfer_id = $1
		ORDER BY created_at DESC LIMIT 1`, id).Scan(&fromState, &toState)
	require.NoError(t, err)
	assert.Equal(t, "completed", fromState, "transition must start from completed")
	assert.Equal(t, "returned", toState, "transition must end in returned")
}

// TestReturn_InvestorNotificationCreated verifies that the Return handler creates
// an investor notification for the returned deposit.
func TestReturn_InvestorNotificationCreated(t *testing.T) {
	db := getReturnTestDB(t)
	defer db.Close()

	id := insertCompletedTransfer(t, db, 120000)
	defer cleanupReturnTransfer(t, db, id)

	gin.SetMode(gin.TestMode)
	r := gin.New()
	svc := NewService(db, state.New(db), nil, nil, ledger.NewService(db))
	handler := NewHandler(svc, Config{ReturnFeeCents: 3000}, notification.NewRepo(db))
	r.POST("/deposits/:id/return", handler.Return)

	body, _ := json.Marshal(map[string]string{
		"reason_code": "frozen_account",
	})
	req := httptest.NewRequest(http.MethodPost, "/deposits/"+id.String()+"/return", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	require.Equal(t, http.StatusOK, w.Code)

	var resp map[string]any
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &resp))
	data := resp["data"].(map[string]any)
	assert.True(t, data["investor_notified"].(bool), "investor_notified must be true")

	var notifCount int
	err := db.QueryRowContext(context.Background(),
		`SELECT COUNT(*) FROM notifications WHERE transfer_id = $1 AND type = 'returned'`,
		id.String()).Scan(&notifCount)
	require.NoError(t, err)
	assert.Equal(t, 1, notifCount, "exactly one returned notification must be created")
}
