package deposit

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"

	"github.com/apex/mcd/internal/funding"
	"github.com/apex/mcd/internal/ledger"
	"github.com/apex/mcd/internal/models"
	"github.com/apex/mcd/internal/state"
	"github.com/apex/mcd/internal/vendor"
	"github.com/google/uuid"
)

// transferSelectCols is the ordered column list used in all transfer SELECT queries.
const transferSelectCols = `
	id, account_id, amount_cents, declared_amount_cents, status, flagged,
	flag_reason, contribution_type, vendor_transaction_id, micr_routing,
	micr_account, micr_serial, micr_confidence, ocr_amount_cents,
	front_image_ref, back_image_ref, settlement_batch_id, return_reason,
	created_at, updated_at`

// SubmitRequest contains all data from the multipart form, prepared by the handler.
type SubmitRequest struct {
	TransferID          uuid.UUID // pre-generated by handler so image dir matches transfer ID
	AccountID           string
	AmountCents         int64
	DeclaredAmountCents int64
	FrontImageRef       string // absolute path saved by handler before calling service
	BackImageRef        string
	// VendorScenario explicitly controls which stub response is returned.
	// If empty, the stub falls back to the account ID suffix. Defaults to CLEAN_PASS.
	VendorScenario string
}

// Service orchestrates the full deposit pipeline.
type Service struct {
	db      *sql.DB
	machine *state.Machine
	vendor  vendor.Service
	funding *funding.Service
	ledger  *ledger.Service
}

// NewService creates a deposit Service with all dependencies wired in.
func NewService(db *sql.DB, machine *state.Machine, vnd vendor.Service,
	fund *funding.Service, led *ledger.Service) *Service {
	return &Service{db: db, machine: machine, vendor: vnd, funding: fund, ledger: led}
}

// Submit runs the full deposit pipeline synchronously:
// Create(Requested) → Validating → Analyzing → Approved → FundsPosted
// OR → Rejected at any failure point
// OR → Analyzing (flagged=true) when vendor flags for review.
func (s *Service) Submit(ctx context.Context, req *SubmitRequest) (*models.Transfer, error) {
	// 1. Create transfer in Requested state
	transfer := &models.Transfer{
		ID:                  req.TransferID,
		AccountID:           req.AccountID,
		AmountCents:         req.AmountCents,
		DeclaredAmountCents: req.DeclaredAmountCents,
		Status:              models.StatusRequested,
		FrontImageRef:       &req.FrontImageRef,
		BackImageRef:        &req.BackImageRef,
	}
	if err := s.createTransfer(ctx, transfer); err != nil {
		return nil, err
	}

	// NOTE: Steps 2-6 use separate transactions for each state transition before the
	// critical section. If the server crashes between commits, a transfer may be stuck
	// in an intermediate state (e.g., Validating with no vendor result). This is acceptable
	// for the demo — the critical section (Analyzing→Approved→FundsPosted + ledger posting)
	// is correctly atomic. Production would use a saga pattern or outbox table.

	// 2. Transition Requested → Validating
	tx1, err := s.machine.BeginAndTransition(ctx, transfer.ID,
		models.StatusRequested, models.StatusValidating, "system", nil)
	if err != nil {
		return nil, err
	}
	tx1.Commit()
	transfer.Status = models.StatusValidating

	// 3. Call vendor stub
	vendorReq := &vendor.Request{
		TransferID:          transfer.ID.String(),
		AccountID:           transfer.AccountID,
		FrontImageRef:       req.FrontImageRef,
		BackImageRef:        req.BackImageRef,
		DeclaredAmountCents: transfer.DeclaredAmountCents,
		Scenario:            req.VendorScenario,
	}
	vendorResp, err := s.vendor.Validate(ctx, vendorReq)
	if err != nil {
		return nil, fmt.Errorf("deposit: vendor validation: %w", err)
	}

	// 4. Store vendor result on transfer
	s.updateTransferVendorData(ctx, transfer, vendorResp)

	// 5. Handle vendor failure
	if vendorResp.Status == "fail" {
		tx, _ := s.machine.BeginAndTransition(ctx, transfer.ID,
			models.StatusValidating, models.StatusRejected, "system",
			map[string]any{"vendor_error": vendorResp.ErrorCode})
		tx.Commit()
		transfer.Status = models.StatusRejected
		return transfer, nil
	}

	// 6. Validating → Analyzing (pass or flagged)
	flagged := vendorResp.Status == "flagged"
	flagReason := ""
	if flagged {
		if vendorResp.MICRData == nil {
			flagReason = "micr_failure"
		} else {
			flagReason = "amount_mismatch"
		}
	}
	tx2, err := s.machine.BeginAndTransition(ctx, transfer.ID,
		models.StatusValidating, models.StatusAnalyzing, "system",
		map[string]any{"flagged": flagged, "flag_reason": flagReason})
	if err != nil {
		return nil, err
	}
	// Update flagged status in same tx
	if _, err := tx2.ExecContext(ctx,
		`UPDATE transfers SET flagged=$1, flag_reason=$2, updated_at=NOW() WHERE id=$3`,
		flagged, flagReason, transfer.ID); err != nil {
		tx2.Rollback()
		return nil, fmt.Errorf("deposit: updating flagged status: %w", err)
	}
	tx2.Commit()
	transfer.Status = models.StatusAnalyzing
	transfer.Flagged = flagged
	if flagReason != "" {
		transfer.FlagReason = &flagReason
	}

	// 7. If flagged, stop here — goes to operator queue
	if flagged {
		return transfer, nil
	}

	// 8. Apply funding rules (Analyzing state)
	ruleResult, err := s.funding.ApplyRules(ctx, transfer, vendorResp)
	if err != nil {
		tx, _ := s.machine.BeginAndTransition(ctx, transfer.ID,
			models.StatusAnalyzing, models.StatusRejected, "system",
			map[string]any{"rule_failure": err.Error()})
		tx.Commit()
		transfer.Status = models.StatusRejected
		return transfer, nil
	}

	// 9. Set contribution type on transfer if determined
	if ruleResult.ContributionType != "" {
		if _, err := s.db.ExecContext(ctx,
			`UPDATE transfers SET contribution_type=$1, updated_at=NOW() WHERE id=$2`,
			ruleResult.ContributionType, transfer.ID); err != nil {
			return nil, fmt.Errorf("deposit: setting contribution type: %w", err)
		}
		ct := ruleResult.ContributionType
		transfer.ContributionType = &ct
	}

	// 10. Analyzing → Approved → FundsPosted in single transaction
	return s.ApproveAndPost(ctx, transfer, ruleResult.OmnibusAccountID, "system")
}

// ApproveAndPost transitions Analyzing→Approved→FundsPosted and posts ledger entry,
// all in a single Postgres transaction. Exported so the operator service can call it
// when approving flagged deposits.
func (s *Service) ApproveAndPost(ctx context.Context, transfer *models.Transfer,
	omnibusAccountID, triggeredBy string) (*models.Transfer, error) {

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("deposit: beginning approval transaction: %w", err)
	}
	defer tx.Rollback()

	// Analyzing → Approved
	if err := s.machine.Transition(ctx, tx, transfer.ID,
		models.StatusAnalyzing, models.StatusApproved, triggeredBy, nil); err != nil {
		return nil, fmt.Errorf("deposit: transitioning to approved: %w", err)
	}

	// Post ledger entry (omnibus → investor)
	if err := s.ledger.PostFundsTx(ctx, tx, transfer, omnibusAccountID); err != nil {
		return nil, fmt.Errorf("deposit: posting funds: %w", err)
	}

	// Approved → FundsPosted
	if err := s.machine.Transition(ctx, tx, transfer.ID,
		models.StatusApproved, models.StatusFundsPosted, triggeredBy, nil); err != nil {
		return nil, fmt.Errorf("deposit: transitioning to funds_posted: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("deposit: committing approval: %w", err)
	}

	transfer.Status = models.StatusFundsPosted
	return transfer, nil
}

// GetByID fetches a transfer and its full state history.
func (s *Service) GetByID(ctx context.Context, id uuid.UUID) (*models.Transfer, []models.StateTransition, error) {
	row := s.db.QueryRowContext(ctx,
		`SELECT`+transferSelectCols+` FROM transfers WHERE id = $1`, id)
	transfer, err := scanTransfer(row.Scan)
	if err == sql.ErrNoRows {
		return nil, nil, models.ErrTransferNotFound
	}
	if err != nil {
		return nil, nil, fmt.Errorf("deposit: getting transfer %s: %w", id, err)
	}

	history, err := s.getStateHistory(ctx, id)
	if err != nil {
		return nil, nil, err
	}

	return transfer, history, nil
}

// List returns transfers with optional filters and pagination.
func (s *Service) List(ctx context.Context, status, accountID string, limit, offset int) ([]*models.Transfer, int, error) {
	where := "WHERE 1=1"
	args := []any{}
	argNum := 1

	if status != "" {
		where += fmt.Sprintf(" AND status = $%d", argNum)
		args = append(args, status)
		argNum++
	}
	if accountID != "" {
		where += fmt.Sprintf(" AND account_id = $%d", argNum)
		args = append(args, accountID)
		argNum++
	}

	var total int
	if err := s.db.QueryRowContext(ctx,
		"SELECT COUNT(*) FROM transfers "+where, args...).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("deposit: counting transfers: %w", err)
	}

	query := `SELECT` + transferSelectCols + ` FROM transfers ` + where +
		fmt.Sprintf(" ORDER BY created_at DESC LIMIT $%d OFFSET $%d", argNum, argNum+1)
	args = append(args, limit, offset)

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, 0, fmt.Errorf("deposit: listing transfers: %w", err)
	}
	defer rows.Close()

	var transfers []*models.Transfer
	for rows.Next() {
		t, err := scanTransfer(rows.Scan)
		if err != nil {
			return nil, 0, fmt.Errorf("deposit: scanning transfer row: %w", err)
		}
		transfers = append(transfers, t)
	}
	return transfers, total, rows.Err()
}

// ProcessReturn handles a check return: Completed→Returned + two reversal ledger entries.
func (s *Service) ProcessReturn(ctx context.Context, transferID uuid.UUID,
	returnReason string, returnFeeCents int64) (*models.Transfer, error) {

	// Fetch the transfer
	row := s.db.QueryRowContext(ctx,
		`SELECT`+transferSelectCols+` FROM transfers WHERE id = $1`, transferID)
	transfer, err := scanTransfer(row.Scan)
	if err == sql.ErrNoRows {
		return nil, models.ErrTransferNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("deposit: getting transfer for return %s: %w", transferID, err)
	}

	if transfer.Status != models.StatusCompleted {
		return nil, models.ErrTransferNotReturnable
	}

	omnibusAccountID, err := s.getOmnibusAccountID(ctx, transfer.AccountID)
	if err != nil {
		return nil, err
	}

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("deposit: beginning return transaction: %w", err)
	}
	defer tx.Rollback()

	// Completed → Returned
	if err := s.machine.Transition(ctx, tx, transferID,
		models.StatusCompleted, models.StatusReturned, "operator",
		map[string]any{"return_reason": returnReason}); err != nil {
		return nil, fmt.Errorf("deposit: transitioning to returned: %w", err)
	}

	// Post reversal + fee ledger entries
	if err := s.ledger.PostReversal(ctx, tx, transfer, omnibusAccountID, returnFeeCents); err != nil {
		return nil, fmt.Errorf("deposit: posting reversal: %w", err)
	}

	// Store return reason
	if _, err := tx.ExecContext(ctx,
		`UPDATE transfers SET return_reason=$1, updated_at=NOW() WHERE id=$2`,
		returnReason, transferID); err != nil {
		return nil, fmt.Errorf("deposit: storing return reason: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("deposit: committing return: %w", err)
	}

	transfer.Status = models.StatusReturned
	transfer.ReturnReason = &returnReason
	return transfer, nil
}

// createTransfer inserts a new transfer row in Requested state.
func (s *Service) createTransfer(ctx context.Context, t *models.Transfer) error {
	_, err := s.db.ExecContext(ctx, `
		INSERT INTO transfers (id, account_id, amount_cents, declared_amount_cents, status, front_image_ref, back_image_ref)
		VALUES ($1, $2, $3, $4, $5, $6, $7)`,
		t.ID, t.AccountID, t.AmountCents, t.DeclaredAmountCents,
		string(t.Status), t.FrontImageRef, t.BackImageRef)
	if err != nil {
		return fmt.Errorf("deposit: creating transfer: %w", err)
	}
	return nil
}

// updateTransferVendorData stores vendor response fields on the transfer record.
func (s *Service) updateTransferVendorData(ctx context.Context, t *models.Transfer, resp *vendor.Response) {
	var (
		micrRouting, micrAccount, micrSerial *string
		micrConfidence                        *float64
	)
	if resp.MICRData != nil {
		micrRouting = &resp.MICRData.RoutingNumber
		micrAccount = &resp.MICRData.AccountNumber
		micrSerial = &resp.MICRData.CheckSerial
		micrConfidence = &resp.MICRData.Confidence
		t.MICRRouting = micrRouting
		t.MICRAccount = micrAccount
		t.MICRSerial = micrSerial
		t.MICRConfidence = micrConfidence
	}
	t.VendorTransactionID = &resp.TransactionID
	t.OCRAmountCents = resp.OCRAmountCents

	if _, err := s.db.ExecContext(ctx, `
		UPDATE transfers SET
			vendor_transaction_id = $1,
			micr_routing = $2,
			micr_account = $3,
			micr_serial = $4,
			micr_confidence = $5,
			ocr_amount_cents = $6,
			updated_at = NOW()
		WHERE id = $7`,
		resp.TransactionID, micrRouting, micrAccount, micrSerial,
		micrConfidence, resp.OCRAmountCents, t.ID); err != nil {
		// Non-fatal: log but continue — vendor data is supplementary
		fmt.Printf("deposit: updating vendor data for %s: %v\n", t.ID, err)
	}
}

// getStateHistory fetches all state transitions for a transfer, ordered by time.
func (s *Service) getStateHistory(ctx context.Context, transferID uuid.UUID) ([]models.StateTransition, error) {
	rows, err := s.db.QueryContext(ctx, `
		SELECT id, transfer_id, from_state, to_state, triggered_by, metadata, created_at
		FROM state_transitions
		WHERE transfer_id = $1
		ORDER BY created_at ASC`, transferID)
	if err != nil {
		return nil, fmt.Errorf("deposit: getting state history for %s: %w", transferID, err)
	}
	defer rows.Close()

	var history []models.StateTransition
	for rows.Next() {
		var st models.StateTransition
		var metaRaw []byte
		if err := rows.Scan(
			&st.ID, &st.TransferID, &st.FromState, &st.ToState,
			&st.TriggeredBy, &metaRaw, &st.CreatedAt); err != nil {
			return nil, fmt.Errorf("deposit: scanning state transition: %w", err)
		}
		if metaRaw != nil {
			_ = json.Unmarshal(metaRaw, &st.Metadata)
		}
		history = append(history, st)
	}
	return history, rows.Err()
}

// getOmnibusAccountID resolves the omnibus account for an investor account.
func (s *Service) getOmnibusAccountID(ctx context.Context, accountID string) (string, error) {
	var omnibusID string
	err := s.db.QueryRowContext(ctx, `
		SELECT c.omnibus_account_id
		FROM accounts a
		JOIN correspondents c ON c.id = a.correspondent_id
		WHERE a.id = $1`, accountID).Scan(&omnibusID)
	if err == sql.ErrNoRows {
		return "", fmt.Errorf("deposit: %w: %s", models.ErrAccountNotFound, accountID)
	}
	if err != nil {
		return "", fmt.Errorf("deposit: getting omnibus account for %s: %w", accountID, err)
	}
	return omnibusID, nil
}

// scanTransfer scans a transfer row using the provided scan function.
// Accepts row.Scan or rows.Scan for reuse across single and multi-row queries.
func scanTransfer(scanFn func(dest ...any) error) (*models.Transfer, error) {
	var t models.Transfer
	var settlementBatchIDStr sql.NullString
	err := scanFn(
		&t.ID, &t.AccountID, &t.AmountCents, &t.DeclaredAmountCents,
		&t.Status, &t.Flagged, &t.FlagReason, &t.ContributionType,
		&t.VendorTransactionID, &t.MICRRouting, &t.MICRAccount,
		&t.MICRSerial, &t.MICRConfidence, &t.OCRAmountCents,
		&t.FrontImageRef, &t.BackImageRef, &settlementBatchIDStr,
		&t.ReturnReason, &t.CreatedAt, &t.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	if settlementBatchIDStr.Valid {
		id, _ := uuid.Parse(settlementBatchIDStr.String)
		t.SettlementBatchID = &id
	}
	return &t, nil
}
